package com.back.fortesupermercados.entities.enums;

public enum SubcategoriaHigienePessoal {
    ABASORVENTE,
    APARELHODEPILADOR,
    CONDICIONADOR,
    CREMEDENTAL,
    CREMES,
    DESODORANTE,
    ESCOVACAPILAR,
    ESCOVADENTAL,
    ESPONJABANHO,
    FRALDA,
    HIGIENEBOCAL,
    PAPELHIGIENICO,
    PRESERVATIVO,
    SABONETEBARRA,
    SABONETELIQUIDO,
    SHAMPOO,
    TALCOS,
    TOALHAUMEDECIDO,
    PRODUTOSDIVERSOS,

}
