package com.back.fortesupermercados.entities.enums;

public enum Subcategoria {
    ACUCAR,
    ARROZ,
    AZEITE,
    FARINHA,
    FAROFA,
    FEIJAO,
    GRAOS,
    MASSAS,
    OLEO,
    OVO,
    SAL,
    VINAGRE,

    REFRESCO,
    AGUASEMGAS,
    AGUACOMGAS,
    SUCO,
    REFRIGERANTEDOISLITROSORIGINAL,
    REFRIGERANTEUMEMEIOLITROORIGINAL,
    REFRIGERANTEUMLITROORIGINAL,
    REFRIGERANTEMEIOLITROORIGINAL,
    REFRIGERANTELATAORIGINAL,
    REFRIGERANTEPEQUENOORIGINAL,
    REFRIGERANTEDOISLITROSZERO,
    REFRIGERANTEUMEMEIOLITROZERO,
    REFRIGERANTEUMLITROZERO,
    REFRIGERANTEMEIOLITROZERO,
    REFRIGERANTELATAZERO,
    REFRIGERANTEPEQUENOZERO,
    ENEGETICOLATA,
    ENEGETICOGARRAFA,
    


}
