package com.back.fortesupermercados.entities.enums;

public enum SubcategoriaLimpeza {
    AGUASANITARIA,
    ALCOOLGEL,
    ALCOOLLIQUIDO,
    AMACIANTE,
    DETERGENTEEMPO,
    DETERGENTELIQUIDO,
    DESENGORDURANTE,
    DESINFETANTE,
    DESODORIZADOR,
    LAVAROUPASLIQUIDO,
    LIMPADORESDIVERSOS,
    MULTIINSETICIDA,
    MULTIUSO,
    PANO,
    PRODUTOSCARRO,
    REPELENTE,
    SABAOEMBARRA,
    SABAOEMPO,
    SABAOLIQUIDO,
    SACOLIXO,
    UTENCILIOSPARALIMPEZA,
    PRODUTOSDIVERSOS,

}
